@file:Suppress("DEPRECATION")

package iooojik.casein

class StaticVars {
    //название настроек
    val preferencesName = "MAIN PREFERENCES"
    val SOCKET_URL = "http://188.127.254.149:3000"
    val API_URL = "http://157.230.123.200:8787"
    val NOTIFICATIONS_CHANNEL = "NOTIFICATIONS_CHANNEL"
    val NOTIFICATION_ID = 102
    val PREFERENCES_CURRENT_USER_TOKEN = "CURRENT_USER_TOKEN"
    val PREFERENCES_CURRENT_USER_NICKNAME = "CURRENT_USER_NICKNAME"
    val PREFERENCES_CURRENT_USER_NAME = "CURRENT_USER_NAME"
    val PREFERENCES_CURRENT_USER_ACCOUNT_TYPE = "ACCOUNT_TYPE"
    val PREFERENCES_CURRENT_USER_NAV_MENU = "NAV_MENU"
    val PREFERENCES_CURRENT_USER_START_FRAGMENT = "START_FRAGMENT"
    val PREFERENCES_USER_ID = "USER_ID"
    val PREFERENCES_PARENT_ID = "PARENT_ID"
    val PREFERENCES_PARENT_NAME = "PARENT_NAME"
}